### PR TITLE
Import unsafeCoerce# from GHC.Exts, not GHC.Base

### PR DESCRIPTION
**Pull request by RyanGlScott**
`attoparsec` fails to build with GHC HEAD (8.11) after [this commit](https://gitlab.haskell.org/ghc/ghc/commit/74ad75e87317196c600dfabc61aee1b87d95c214), which moves `unsafeCoerce#` from `GHC.{Base,Prim}` to `Unsafe.Coerce`:

```
[ 5 of 21] Compiling Data.Attoparsec.Text.Buffer ( Data/Attoparsec/Text/Buffer.hs, /home/rgscott/Documents/Hacking/Haskell/staging/dist-newstyle/build/x86_64-linux/ghc-8.11.0.20200222/attoparsec-0.13.2.3/build/Data/Attoparsec/Text/Buffer.o, /home/rgscott/Documents/Hacking/Haskell/staging/dist-newstyle/build/x86_64-linux/ghc-8.11.0.20200222/attoparsec-0.13.2.3/build/Data/Attoparsec/Text/Buffer.dyn_o )

Data/Attoparsec/Text/Buffer.hs:51:43: error:
    Module ‘GHC.Base’ does not export ‘unsafeCoerce#’
   |
51 | import GHC.Base (Int(..), indexIntArray#, unsafeCoerce#, writeIntArray#)
   |                                           ^^^^^^^^^^^^^
```

This patch fixes the issue by instead importing `unsafeCoerce#` from `GHC.Exts`, which has better API stability. While I was in town, I went ahead and switched all other `GHC.Base` imports to `GHC.Exts` to make the code future-proof against other `GHC.Base` API changes in the future.

### CODE REVIEW

**Comment by andrewthad** [comment]
It would be nice to see this merged. It's helpful when master builds with GHC head.
